import Footer from "./Component/Footer";
import Navigation from "./Component/Navigation";
import "./globals.css";
import StoreProvider from "./Redux/Provider";

export const metadata = {
  title: "AKASHA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Navigation />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
